# Generated by Django 3.2.4 on 2023-01-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='адрес')),
                ('lon', models.FloatField(blank=True, verbose_name='Долгота')),
                ('lat', models.FloatField(blank=True, verbose_name='Широта')),
            ],
            options={
                'verbose_name': 'координаты заказа',
                'verbose_name_plural': 'координаты заказа',
            },
        ),
    ]
