# Generated by Django 3.2.4 on 2022-12-07 06:49

from django.db import migrations

def order_element_price(apps, schema_editor):
    OrderElement = apps.get_model('foodcartapp', 'OrderElement')

    for element in OrderElement.objects.all().iterator():
        element.price = element.product.price
        element.save()

class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_rename_orderelements_orderelement'),
    ]

    operations = [
        migrations.RunPython(order_element_price)
    ]
