# Generated by Django 3.2.4 on 2022-12-09 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_auto_20221207_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'Необработанный'), ('Done', 'Обработанный'), ('Progress', 'На сборке'), ('Go', 'Доставляется')], db_index=True, default='Необработанный', max_length=20, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='orderelement',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена товара'),
        ),
    ]
