# Generated by Django 3.2.4 on 2022-12-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_alter_orderelement_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderelement',
            name='comment',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Комментарий к заказу'),
        ),
    ]
