# Generated by Django 3.2.4 on 2022-12-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_orderelement_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderelement',
            name='comment',
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Комментарий к заказу'),
        ),
    ]
