# Generated by Django 3.2.4 on 2022-12-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_auto_20221210_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_form',
            field=models.CharField(choices=[('right_now_pay', 'Электронно'), ('delivery_pay_cash', 'Наличными после доставки'), ('delivery_pay_card', 'Картой после доставки')], db_index=True, default='delivery_pay_cash', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
