# Generated by Django 3.2.4 on 2022-12-28 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0052_order_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='called',
            new_name='called_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='delivered',
            new_name='delivered_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='registered',
            new_name='registered_at',
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к заказу'),
        ),
        migrations.AlterField(
            model_name='orderelement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_elements', to='foodcartapp.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='orderelement',
            name='quantity',
            field=models.IntegerField(verbose_name='Количество данного товара'),
        ),
    ]
