# Generated by Django 3.2.4 on 2022-12-28 06:24

from django.db import migrations

def replace_null_to_str(apps, schema_editor):
    Order = apps.get_model('foodcartapp', 'Order')
    for order in Order.objects.all().iterator():
        if order.comment == None:
            order.comment = ''
            order.save()

class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_auto_20221228_0920'),
    ]

    operations = [
        migrations.RunPython(replace_null_to_str)
    ]
