# Generated by Django 3.2.4 on 2023-01-10 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0057_auto_20230110_1116'),
    ]

    operations = [
        migrations.DeleteModel('Coordinates')
    ]
