# Generated by Django 3.2.15 on 2023-04-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0059_auto_20230116_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_form',
            field=models.CharField(choices=[('right_now_pay', 'Электронно'), ('delivery_pay_cash', 'Наличными после доставки'), ('delivery_pay_card', 'Картой после доставки')], db_index=True, default='delivery_pay_cash', max_length=50, verbose_name='Способ оплаты'),
        ),
    ]
